### ISSUE TITLE
BTM Einheit Redundant

### ISSUE THREAD

**Issue by AdrianBeilharz** [AdrianBeilharz/EDB-Apo#32]
Für jede Darreichungsform gibt es nur eine mögliche Darreichungsform.
Es sollte statt die Einheit in einem Drop-Down Menü auszuwählen die Einheit nur als Information zusätzlich zur Darreichungsform angezeigt werden.

**Comment by LarsMaronde** [comment]
Rezeptursubstanz hat aber zwei Darreichungsformen, vielleicht sind auch noch nicht alle möglichen Darreichungsformen abgedeckt

**Comment by AdrianBeilharz** [comment]
I see BtmAddModal hat 2 aber wir verwenden das NeuesBtmModal und da gibt es nur 1.
